---

- name: Install Neutron midonet packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - neutron-server
    - python-networking-midonet-ext
    - python-neutronclient
    - python-neutron-lbaas
