---

- name: Install Neutron midonet packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - openstack-neutron
    - python-networking-midonet-ext
    - python-neutronclient
    - openstack-neutron-ml2
    - python-neutron-lbaas
